### PR TITLE
[C++] Add RE2 version of regex-redux benchmark

### PR DESCRIPTION
**Pull request by dungwinux**
- [x] Rewrite in RE2 (install dependency with `sudo apt install libre2-9 libre2-dev`)
- [ ] Rewrite in CTRE (Blocked: Does not implement Replace function)

### CODE REVIEW

**Comment by nicovank** [comment]
Let's just make this patch RE2 and have another one later for CTRE if you get that working.

I'm assuming you are compiling this fine because you have RE2 installed locally, could you make a small `FetchContent` cmake file so it works in isolation?

- We can just have something like this in the Makefile:
```
compile:
	cmake . -B build -DCMAKE_BUILD_TYPE=Release
run:
	./build/regexredux_run 0 < ../../regexredux-input5000000.txt
<...>
```

 - Add a `.gitignore` for the `build` directory.

Here is a CMake file I was just working on that has a FetchContent and LTO example: https://github.com/plasma-umass/cwhy/blob/main/mutations/CMakeLists.txt

**Comment by nicovank** [comment]
Also, I believe you want to use something like this for OpenMP:

```
find_package(OpenMP REQUIRED)
target_link_libraries(<target> PRIVATE OpenMP::OpenMP_CXX)
```

**Comment by nicovank** [comment]
Nevermind, I just saw you can install the dependency through APT. This is fine.

**Review by nicovank — APPROVED** [review]
This is perfect, thank you.

Next time, one nice thing is to split the copy files commit from the actual change commit, it makes it easier to compare V1 and V2 by just looking at the second commit.
